project_novis/api/urls.py
from django.urls import path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers
from rest_framework.authtoken import views
from rest_framework.permissions import AllowAny

from project_novis.accounts.views import CurrentUserAPIView
from project_novis.api.apps import ApiConfig
from project_novis.callsign.views import CountryViewSet, DXCCEntryViewSet, CallsignViewSet, UserCallsignViewSet, \
    CallsignCreateAPIView, DMRIDViewSet, CallsignPrefixViewSet, RepeaterViewSet, APRSPasscodeView

app_name = ApiConfig.name
schema_view = get_schema_view(
    openapi.Info(
        title="project novis API",
        default_version='v1',
        description="Ham radio API provided by project novis. API is in beta stage and not stable.",
        terms_of_service="https://www.project-novis.org/terms/",
        contact=openapi.Contact(email="help@project-novis.org", url="https://www.project-novis.org"),
        license=openapi.License(name="MIT License", url="https://choosealicense.com/licenses/mit/"),
    ),
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=(AllowAny,),
)


router = routers.SimpleRouter()
router.register(r'country', CountryViewSet)
router.register(r'dxcc', DXCCEntryViewSet)
router.register(r'callsign', CallsignViewSet)
router.register(r'dmr', DMRIDViewSet)
router.register(r'prefix', CallsignPrefixViewSet)
router.register(r'repeater', RepeaterViewSet)
router.register(r'user/callsign', UserCallsignViewSet)

urlpatterns = [
    path('callsign', CallsignCreateAPIView.as_view(), name="callsign-create"),
    path('user', CurrentUserAPIView.as_view(), name="userinfo-retrieve"),
    path('user/callsign/<str:name>/aprs_passcode', APRSPasscodeView.as_view(), name="aprs-passcode"),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=None), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=None), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=None), name='schema-redoc'),
    path('api-token-auth/', views.obtain_auth_token)
]

urlpatterns += router.urls

project_novis/callsign/urls.py
from django.urls import path

from .views import CallsignDetailView, CallsignCreate, CallsignUpdate, CallsignClaimView, RepeaterUpdate, ClubUpdate,\
    CallsignAutocomplete

app_name = "callsign"

urlpatterns = [
    path('add/', CallsignCreate.as_view(), name='callsign-html-create'),
    path('autocomplete/', CallsignAutocomplete.as_view(), name='callsign-autocomplete'),

    path('<slug>/', CallsignDetailView.as_view(), name='callsign-html-detail'),
    path('<slug>/change', CallsignUpdate.as_view(), name='callsign-html-update'),
    path('<slug>/repeater/change', RepeaterUpdate.as_view(), name='repeater-html-update'),
    path('<slug>/club/change', ClubUpdate.as_view(), name='club-html-update'),
    path('<slug>/claim', CallsignClaimView.as_view(), name='callsign-html-claim'),
]

project_novis/main/urls.py
from django.urls import path
from django.contrib.flatpages import views

from .views import HomePageView, EmptyView, VersionView, RobotsView

urlpatterns = [
    path('', HomePageView.as_view(), name="index"),
    path('version', VersionView.as_view(), name="version"),
    path('healthz', EmptyView.as_view(), name="healthz"),  # Only for reference, handled in HealthCheckMiddleware
    path('readiness', EmptyView.as_view(), name="readiness"),  # Only for reference, handled in HealthCheckMiddleware
    path('robots.txt', RobotsView.as_view(), name="robots"),

    # Flatpages
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('privacy/', views.flatpage, {'url': '/privacy/'}, name='privacy'),
    path('terms/', views.flatpage, {'url': '/terms/'}, name='terms'),
    path('contrib/', views.flatpage, {'url': '/contrib/'}, name='contrib'),
]

project_novis/radius/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    #path('api/radius/auth', RadiusAuthView.as_view()),
]

project_novis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.views.decorators.cache import cache_page

from project_novis.main.sitemaps import StaticViewSitemap
from project_novis.callsign.sitemaps import CallsignSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'flatpages': FlatPageSitemap,
    'callsigns': CallsignSitemap
}

urlpatterns = [
    path('', include('project_novis.main.urls')),
    path('accounts/', include('project_novis.accounts.urls')),
    path('.well-known/change-password', RedirectView.as_view(pattern_name='account_change_password', permanent=False)),
    path('sitemap.xml', cache_page(3600)(sitemaps_views.index), {'sitemaps': sitemaps}, name="sitemap"),
    path('sitemap-<section>.xml', cache_page(3600)(sitemaps_views.sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('c/', include('project_novis.callsign.urls')),
    path("api/v1/", include("project_novis.api.urls", namespace='v1')),
    path('', include('project_novis.radius.urls')),
    path('admin/', admin.site.urls),
    path('docs/', RedirectView.as_view(url=settings.DOCS_URL, permanent=False), name='docs'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.views import defaults as default_views
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

project_novis/callsign/models.py
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.postgres.fields import JSONField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import PermissionDenied, ValidationError

from .enums import CALLSIGN_TYPES, CONTINENTS, CTCSS, RF_MODES, BLACKLIST_REASONS,\
    LOCATION_SOURCE_CHOICES, LOCATION_SOURCE_PRIORITY
from .utils import CallsignField, CQZoneField, ITUZoneField, ITURegionField, WikidataObjectField,\
    generate_aprs_passcode, point_to_grid, grid_to_point, get_sentinel_user


class BaseModel(models.Model):
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified"), auto_now=True)

    class Meta:
        abstract = True


class LocationBaseModel(BaseModel):
    location = models.PointField(null=True, blank=True)

    class Meta:
        abstract = True

    def _grid(self, high_accuracy: bool = True) -> str:
        if not self.location:
            return ""

        return point_to_grid(self.location, high_accuracy=high_accuracy)

    @property
    def grid(self):
        return self._grid(high_accuracy=True)

    @grid.setter
    def grid(self, grid: str):
        self.location = grid_to_point(grid)

    @property
    def aprs_fi_url(self) -> str:
        return f"https://aprs.fi/#!addr={self.grid}"

    # @property
    # def cq_zone(self) -> int:
    #     raise NotImplementedError
    #
    # @property
    # def itu_zone(self) -> int:
    #     raise NotImplementedError
    #
    # @property
    # def itu_region(self) -> int:
    #     raise NotImplementedError
    #
    # @property
    # def continent(self) -> str:
    #     raise NotImplementedError
    #
    # @property
    # def dxcc(self) -> int:
    #     raise NotImplementedError
    #
    # @property
    # def country(self) -> str:
    #     raise NotImplementedError
    #
    # @property
    # def utc_offset(self) -> int:
    #     raise NotImplementedError


class Country(BaseModel):
    name = models.CharField(max_length=64, unique=True, db_index=True)
    alpha_2 = models.CharField(max_length=2, unique=True, db_index=True, help_text="ISO 3166-1 alpha-2 – two-letter country code")
    alpha_3 = models.CharField(max_length=3, unique=True, db_index=True, help_text="ISO 3166-1 alpha-3 – three-letter country code")
    numeric_3 = models.CharField(max_length=3, unique=True, db_index=True, help_text="ISO 3166-1 numeric – three-digit country code")
    wikidata_object = WikidataObjectField(unique=True, db_index=True)

    # Additional Information
    adif_name = models.CharField("ADIF name", max_length=64, db_index=True, blank=True, null=True, help_text="Amateur Data Interchange Format (ADIF) country name")
    geonames_id = models.PositiveIntegerField("Geonames ID", null=True, blank=True)
    osm_relation_id = models.PositiveIntegerField("OSM relation ID", null=True, blank=True, help_text="OpenStreetMap relation ID")
    itu_object_identifier = models.CharField("ITU object identifier", max_length=16, blank=True, null=True, help_text="International Telecommunication Union (ITU) object identifier")
    itu_letter_code = models.CharField("ITU letter code", max_length=3, blank=True, null=True, help_text="International Telecommunication Union (ITU) letter code")
    fips = models.CharField("FIPS", max_length=2, blank=True, null=True, help_text="Federal Information Processing Standards (FIPS) 10-4 standard country code")

    def __str__(self) -> str:
        return self.name

    @property
    def wikidata_url(self) -> str:
        return f"https://www.wikidata.org/wiki/{self.wikidata_object}"

    @property
    def geonames_url(self) -> str:
        if self.geonames_id:
            return f"https://www.geonames.org/{self.geonames_id}"
        else:
            return ""

    @property
    def osm_relation_url(self) -> str:
        if self.osm_relation_id:
            return f"https://www.openstreetmap.org/relation/{self.osm_relation_id}"
        else:
            return ""

    @property
    def world_fact_book_url(self) -> str:
        if self.fips:
            return f"https://www.cia.gov/library/publications/the-world-factbook/geos/{self.fips}.html"
        else:
            return ""


class DXCCEntry(BaseModel):
    name = models.CharField(max_length=64, db_index=True)
    deleted = models.BooleanField(default=False)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "DXCC Entry"
        verbose_name_plural = "DXCC Entries"
        unique_together = ("name", "deleted")


class CallsignPrefix(BaseModel):
    name = models.CharField(max_length=16, unique=True, db_index=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, null=True, blank=True)
    dxcc = models.ForeignKey(DXCCEntry, on_delete=models.PROTECT, null=True, blank=True, verbose_name="DXCC")
    cq_zone = CQZoneField("CQ zone", null=True, blank=True)
    itu_zone = ITUZoneField("ITU zone", null=True, blank=True)
    itu_region = ITURegionField("ITU region", null=True, blank=True)
    continent = models.CharField(choices=CONTINENTS, max_length=2, blank=True)
    location = models.PointField(null=True, blank=True)
    utc_offset = models.FloatField("UTC offset", null=True, blank=True)
    type = models.CharField(choices=CALLSIGN_TYPES, max_length=32, blank=True)

    def __str__(self) -> str:
        return self.name


class CallsignManager(models.Manager):
    def create_callsign(self, callsign: str, created_by_id: int, check_blacklist: bool = True):
        # TODO further validate callsign
        # Check if callsign is blacklisted
        if check_blacklist and CallsignBlacklist.objects.filter(callsign=callsign).exists():
            raise ValidationError("callsign is blacklisted")

        instance = self.create(name=callsign, created_by_id=created_by_id)
        instance.set_default_meta_data()
        instance.save()
        return instance


class Callsign(LocationBaseModel):
    name = CallsignField(unique=True, db_index=True)
    prefix = models.ForeignKey(CallsignPrefix, on_delete=models.PROTECT, null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, null=True, blank=True)
    cq_zone = CQZoneField("CQ zone", null=True, blank=True)
    itu_zone = ITUZoneField("ITU zone", null=True, blank=True)
    itu_region = ITURegionField("ITU region", null=True, blank=True)
    type = models.CharField(choices=CALLSIGN_TYPES, max_length=32, blank=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)
    active = models.BooleanField(default=True)
    issued = models.DateField(null=True, blank=True)
    expired = models.DateField(null=True, blank=True)
    license_type = models.CharField(max_length=64, blank=True)
    dstar = models.BooleanField("D-STAR", default=False)
    identifier = models.CharField(_("Optional identifier"), max_length=128, unique=True, blank=True, null=True)
    website = models.URLField(max_length=128, blank=True, null=True)
    comment = models.TextField(blank=True)
    _official_validated = models.BooleanField(default=False, help_text="Callsign is validated by a government agency")
    _location_source = models.CharField(max_length=32, choices=LOCATION_SOURCE_CHOICES, blank=True)

    lotw_last_activity = models.DateTimeField("LOTW last activity", null=True, blank=True)
    eqsl = models.BooleanField(default=False)

    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET(get_sentinel_user), related_name="callsigns")
    internal_comment = models.TextField(blank=True)
    source = models.CharField(max_length=256, blank=True)
    objects = CallsignManager()

    # TODO(elnappo) make sure a user can not change his name after validation

    def __str__(self) -> str:
        return self.name

    def set_default_meta_data(self):
        prefix = CallsignPrefix.objects.extra(where=["%s LIKE name||'%%'"], params=[self.name]).order_by("-name").first()

        # Add changed fields to ImportCommand._callsign_bulk_create()
        if prefix:
            self.prefix = prefix
            self.country = prefix.country
            self.cq_zone = prefix.cq_zone
            self.itu_zone = prefix.itu_zone
            self.location = prefix.location
            self._location_source = "prefix"

    def get_absolute_url(self) -> str:
        return reverse('callsign:callsign-html-detail', args=[self.name])

    def update_location(self, location: Point, source: str) -> bool:
        # Update location only if new location source has higher priority than current location source.
        # Does no update if new and current location source are equal.
        if LOCATION_SOURCE_PRIORITY.index(source) > LOCATION_SOURCE_PRIORITY.index(self.location_source):
            self.location = location
            self._location_source = source
            return True
        else:
            return False

    @property
    def aprs_passcode(self) -> int:
        if self.official_validated == "false" or self.type == "shortwave_listener":
            # Not a good idea to raise an exception here?
            raise PermissionDenied("callsign is not official assigned or is shortwave listener")
        return generate_aprs_passcode(self.name)

    @property
    def official_validated(self) -> str:
        if self.country and self.country.telecommunicationagency.used_for_official_callsign_import and self._official_validated:
            return "true"
        elif self.country and self.country.telecommunicationagency.used_for_official_callsign_import and not self._official_validated:
            return "false"
        else:
            return "unknown"

    @property

project_novis/radius/views.py
from rest_framework import status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from .serializers import RadiusAuthSerializer


class RadiusAuthView(APIView):
    permission_classes = (AllowAny,)
    serializer_class = RadiusAuthSerializer

    def post(self, request, format=None) -> Response:
        print(request.data)
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})
        serializer.is_valid(raise_exception=True)
        return Response(status=status.HTTP_204_NO_CONTENT)

project_novis/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title_outer %}<title>{% block title %}{{ site.name }} - An Amateur Radio Platform{% endblock %}</title>{% endblock %}
    {% block meta %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=5" name="viewport">
    <meta name="keywords" content="amateur,ham,radio,hamradio,callsign,hamnet,qth,api,oauth">
    <meta name="apple-mobile-web-app-title" content="project novis">
    {% endblock %}
    {% block meta_content %}
    <meta name="description" content="A free and open-source platform for amateur radio related services. Provides a
    comprehensive database with an easy to use and modern API.">
    {% endblock %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/AdminLTE.min.css" %}">
    <link rel="stylesheet" href="{% static "css/skins/skin-blue.min.css" %}">
    <link rel="icon" type="image/svg+xml" sizes="any" href="{% static "img/favicon.svg" %}">
    <link rel="icon" type="image/png" href="{% static "img/favicon_32.png" %}" sizes="32x32">
    <link rel="icon" type="image/png" href="{% static "img/favicon_96.png" %}" sizes="96x96">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">

    {% block extra_head %}{% endblock %}
    <style>
    .navbar-brand {
      padding: 0px;
    }
    .navbar-brand>img {
      height: 100%;
      width: auto;
    }
    </style>
</head>
<body class="{% block body_class %}hold-transition skin-blue layout-boxed layout-top-nav{% endblock %}">
{% block body %}{% endblock body %}
{% block extra_body %}{% endblock %}
{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <script src="{% static "js/adminlte.min.js" %}"></script>
    <script type="text/javascript">
        function process(form){
            if ($(form).has("input").length > 0){
                form = $(form).find("input");
            }
            if ($(form).val().length > 2){
                var getURL = window.location;
                var baseCallsignURL = getURL .protocol + "//" + getURL.host + "/" + "c/";
                location.href = baseCallsignURL + $(form).val();
                $(form).val("");
                return false;
            }
            else{
                return false;
            }
        }
    </script>
{% endblock %}

{% block extra_foot %}{% endblock %}
{% block tracking %}
  <!-- Matomo -->
  <script>
    var _paq = _paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="https://piwik.nerdpol.io/";
      _paq.push(['setTrackerUrl', u+'piwik.php']);
      _paq.push(['setSiteId', '1']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
  <noscript><p><img src="https://piwik.nerdpol.io/piwik.php?idsite=1&amp;rec=1" style="border:0;" alt="" /></p></noscript>
  <!-- End Matomo Code -->
{% endblock %}
</body>
</html>

project_novis/templates/index.html
{% extends 'base.html' %}
{% load static i18n avatar_tags %}

{% block body %}
<div class="wrapper">
    <header class="main-header">
        <nav class="navbar navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
            <a href="{% url 'index' %}" class="navbar-brand"><img src="{% static "img/logo.svg" %}" alt="project novis logo"></a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <i class="fa fa-bars"></i>
            </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse">
            {% block nav_header %}
                {% include 'nav_main_header.html' %}
            {% endblock %}
            <form class="navbar-form navbar-left" role="search" action="#" onsubmit="return process(this);">
                <div class="form-group">
                <input type="text" class="form-control" id="navbar-search-input" name="name" placeholder="Callsign Search" required>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li class="dropdown tasks-menu">
              <!-- Menu Toggle Button -->
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-flag-o"></i>
                <span class="label label-danger">9</span>
              </a>
              <ul class="dropdown-menu">
                <li class="header">9 open validation requests</li>
                <li>
                  <!-- Inner menu: contains the tasks -->
                  <ul class="menu">
                    <li><!-- Task item -->
                      <a href="#">
                        <!-- Task title and progress text -->
                        <h3>
                          Design some buttons
                          <small class="pull-right">20%</small>
                        </h3>
                        <!-- The progress bar -->
                        <div class="progress xs">
                          <!-- Change the css width attribute to simulate progress -->
                          <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                            <span class="sr-only">20% Complete</span>
                          </div>
                        </div>
                      </a>
                    </li>
                    <!-- end task item -->
                  </ul>
                </li>
                <li class="footer">
                  <a href="#">View all validation requests</a>
                </li>
              </ul>
            </li>
            {% endif %}
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <!-- The user image in the navbar-->
                    <img src="{% avatar_url user 160 %}" class="user-image" alt="User Image">
                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                    <span class="hidden-xs">{% if user.name %}{{ user.name }}{% else %}{{ user.email }}{% endif %} <i class="fa fa-sort-down"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                    <!-- The user image in the menu -->
                    <li class="user-header">
                        <img src="{% avatar_url user 160 %}" class="img-circle" alt="User Image">

                        <p>
                        {% if user.name %}{{ user.name }}{% else %}{{ user.email }}{% endif %}
                        <small>Member since {{ user.date_joined|date }}</small>
                        </p>
                    </li>
                    {% if user.is_staff %}
                    <!-- Menu Body -->
                    <li class="user-body">
                        <div class="row">
                        <div class="col-xs-4 text-center">
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </div>
                        </div>
                        <!-- /.row -->
                    </li>
                    {% endif %}
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-left">
                        <a href="{% url "profile_change" %}" class="btn btn-default btn-flat">Settings</a>
                        </div>
                        <div class="pull-right">
                        <a href="{% url 'account_logout' %}" class="btn btn-default btn-flat">Sign out</a>
                        </div>
                    </li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{% url 'account_login' %}"><i class="fa fa-sign-in"></i> Sign in</a></li>
                <li><a href="{% url 'account_signup' %}"><i class="fa fa-user-plus"></i> Sign up</a></li>
                {% endif %}
            </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
        </nav>
    </header>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% block raw_content %}
        <section class="content-header">

        {% block content_header %}
            <h1>
                Page Header
                <small>Optional description</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        {% endblock %}

        </section>

        <section class="content container-fluid">

        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}

        {% block content %}
          <!--------------------------
            | Your Page Content Here |
            -------------------------->
        {% endblock %}

        </section>
        {% endblock %}
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
        <a href="{% url 'privacy' %}">Privacy</a> &bull; <a href="{% url 'terms' %}">Terms</a> &bull; <a href="{% url 'about' %}">About</a> &bull; <a href="https://github.com/elnappo/project-novis" class="fa fa-github"></a>
        </div>
        <!-- Default to the left -->
        Please submit feedback to <a href="mailto:feedback@project-novis.org">feedback@project-novis.org</a>
    </footer>
    <!-- ./wrapper -->
{% endblock %}

project_novis/templates/nav_main_header.html
<ul class="nav navbar-nav">
    {% if user.is_authenticated %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Call Sings <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                {% for call_sign in user.callsign_set.all %}
                    <li><a href="{% url 'callsign:callsign-html-detail' call_sign.name %}">{{ call_sign.name }}</a></li>
                    {% if forloop.last %}
                        <li class="divider"></li>
                    {% endif %}
                {% endfor %}
                <li><a href="{% url 'callsign:callsign-html-create' %}">Add Call Sign</a></li>
            </ul>
        </li>
    {% endif %}
        <li><a href="{% url "project_novis.api:schema-swagger-ui" %}">API</a></li>
        <li><a href="https://project-novis.readthedocs.io/en/latest/">Docs</a></li>
        <li><a href="{% url 'contrib' %}">Contribute</a></li>
</ul>